local callbacks = {}

callbacks.commands = {
    ["n-<leader>fg"] = ":!grep -R  .<Left><Left>",
    ["n-<leader>ff"] = ":!find . -name **<Left>",
    ["n-<leader>fs"] = ":!grep -R  .<Left><Left>",
    ["n-<A-j>"] = "<c-w>j",
    ["n-<A-k>"] = "<c-w>k",
    ["n-<A-h>"] = "<c-w>h",
    ["n-<A-l>"] = "<c-w>l",
    ["n-<A-t>n"] = "<cmd>sp | :term<cr>",
    ["n-<A-t>t"] = "<cmd>sp | :term<cr>",
    ["n-<A-n>s"] = "<cmd>sp | :enew<cr>",
    ["n-<A-n>v"] = "<cmd>vsp | :enew<cr>",
    ["n-<A-n>t"] = "<cmd>tabe<cr>",
    ["n-<A-C>"] = "",
    ["n-<A-z>"] = "",
    ["n-<leader>c"] = ":",
    ["n-<leader>Cn"] = ":",
    ["n-<leader>p"] = "<cmd>lua require('nvim-configs.functions').MdPreview()<cr>",
    ['n-<leader>K'] = "",
    ['n-<leader>gd'] = "",
    ['n-<leader>gD'] = "",
    ['n-<leader>gi'] = "",
    ['n-<leader>gr'] = "",
    ['n-<leader>ga'] = "",
    ['n-<leader>gf'] = "",
    ['n-<leader>gR'] = "",
    ['n-<A-Up>'] = "<cmd>resize +3<cr>",
    ['n-<A-Left>'] = "<cmd>vertical resize +3<cr>",
    ['n-<A-Down>'] = "<cmd>resize -3<cr>",
    ['n-<A-Right>'] = "<cmd>vertical resize -3<cr>",
    ['v->'] = ">gv",
    ['v-<'] = "<gv",
    ['n-<A-e>1'] = "",
    ['n-<A-e>2'] = "",
    ['n-<A-e>3'] = "",
    ['n-<A-e>4'] = "",
    ['n-<A-e>5'] = "",
    ['n-<A-e>0'] = "",
    ['n-<A-t>1'] = "",
    ['n-<A-t>2'] = "",
    ['n-<A-t>3'] = "",
    ['n-<A-t>4'] = "",
    ['n-<A-t>0'] = "",
}

return callbacks

